# Generated by Django 6.0.4 on 2026-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
