# Generated by Django 6.0.4 on 2026-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_syllabus_syllabusitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_files/'),
        ),
        migrations.AddField(
            model_name='syllabusitem',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='syllabusitem',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabusitem',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='item_type',
            field=models.CharField(choices=[('text', 'Text Note'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
