# Generated by Django 6.0.4 on 2026-05-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_predictionlog_flashcard_syllabus_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_hour_start', models.IntegerField(default=0)),
                ('peak_hour_end', models.IntegerField(default=2)),
                ('peak_days', models.JSONField(default=list)),
                ('weekly_intensity', models.JSONField(default=dict)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_pattern', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Pattern',
            },
        ),
    ]
